#! /bin/bash 

# stop script when an error occurs 
set -e 
 
 
psql -q -c "CREATE USER mary SUPERUSER PASSWORD '123'" 
echo "Created Postgres user 'mary'" 
 
 
psql -q -c "CREATE DATABASE playdateapp WITH OWNER mary" 
echo "Created Postgres database 'playdateapp'" 
 
 
cp -r example.env .env 
echo "Created .env containing DATABASE_URL" 
